<?php


namespace App\Helpers\Classes\Service;


use LaravelEasyRepository\Implementations\Eloquent;

class EloquentExtended extends Eloquent
{
    public function selectOnly(array $columns,array $with=[])
    {
        return $this->model->with($with)->select($columns)->get();
    }
    public function update($id, array $data)
    {
        parent::update($id, $data); // TODO: Change the autogenerated stub
        return $this->find($id);
    }

    public function last(){
        return $this->model->latest()->first();
    }
    public function first(){
        return $this->model->first();
    }
    function filters(array $domain = [], $limit = 1,$fields=[])
    {
        $builder=$this->model;

        foreach ($domain as $clause)
            if(count($clause)===3){
                if($clause[1] == 'in')
                    $builder=$builder->whereIn($clause[0],$clause[2]);
                else
                    $builder=$builder->where($clause[0],$clause[1],$clause[2]);
            }
            else
                $builder=$builder->where($clause[0],$clause[1]);

        if($limit !== 1 || $limit !== -1)
            $builder=$builder->limit($limit);

        if($fields)
            $builder=$builder->get($fields);
        else
            $builder=$builder->get();

        if ($limit === 1)
            return $builder->first();
        return $builder;
    }
    public function all($filter=null,$with=[])
    {
        if($filter)
            return $this->model->with($with)->filter($filter)->get();
        return $this->model->with($with)->latest()->get(); // TODO: Change the autogenerated stub
    }
    public function paginate(int $limit=10,array $with=[],$filter=[]):LengthAwarePaginator{
        if(count($filter)!==0 && method_exists($this->model::class,'scopeFilter'))
            return $this->model->filter($filter)->latest()->with($with)->paginate($limit);
        else
            return $this->model->with($with)->latest()->paginate($limit);
    }
    public function all_with($with=[]){
        return $this->model->with($with)->latest()->get();
    }
    public function count():int{
        return  $this->model->count();
    }
}
